name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  notifyWhatsApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Notification WhatsApp
        id: whatsapp-notify
        env:
          account_sid: ${{ SECRETS.twilio_account_sid }}
          auth_token: ${{ SECRETS.twilio_auth_token }}
          to_whatsapp_no: ${{ SECRETS.twilio_to_whatsapp_no }}
          message: "CI 👉🏻 Bruno"
        uses: khaled-ibtikar/whatsapp-push-notify-action@master
